title: Performance Team Münster
fetchPrefix: https://performanceteammuenster.github.io/website
pagesPrefix: Content
primary-color: '#732847'
secondary-color: '#d4c5db'
secondary-light-color: '#e7daed'
