title: Performance Team Münster
fetchPrefix: https://raw.githubusercontent.com/PerformanceTeamMuenster/website/master
pagesPrefix: Content
primary-color: #732847
secondary-color: #d4c5db
secondary-light-color: #e7daed
